### ISSUE TITLE
[Bug] [Android] Dark theme UI issues

### ISSUE THREAD

**Issue by AntoninLoubiere** [ThaaoBlues/CopyPasta#2]
When using a dark theme on an android device, the text of the devices list is invisible because black on a black background. And the text in the bottom that show the current text is illisible for the same reasons.

**Comment by ThaaoBlues** [comment]
A new version is coming in few days with disabled dark mode ^^ It will be back in some versions if we have the time.

**Comment by remialban** [comment]
I disabled the dark mode and I corrected the IP input : the points work. And I left the input to number because I consider that people never use a dns name but it's debatable.
