### ISSUE TITLE
[Bug] [Linux] Incompatibility

### ISSUE THREAD

**Issue by AntoninLoubiere** [ThaaoBlues/CopyPasta#4]
win32clipboard isn't available for linux. May be just add a `try` `execept ImportError` and warn the user when it tries to use this function on linux.

**Comment by ThaaoBlues** [comment]
This software is mainly developped for windows, im afraid that this will not be the only part that doesn't work. I'll put it into a try-catch block but I don't guarantee the full Linux support.

**Comment by ThaaoBlues** [comment]
Fixed, thanks a lot !
