### ISSUE TITLE
[Bug] [Linux] root privilege needed

### ISSUE THREAD

**Issue by AntoninLoubiere** [ThaaoBlues/CopyPasta#5]
The port 80 require root privileges, use another port like 8080 to solve this problem.

**Comment by ThaaoBlues** [comment]
Thanks for the report, I will take a non used port like 5986 to not create a bug, 8080 is used by some other web server.

**Comment by ThaaoBlues** [comment]
changed to port 21053, i close the issue.

**Comment by AntoninLoubiere** [comment]
> Thanks for the report, I will take a non used port like 5986 to not create a bug, 8080 is used by some other web server.

Or if you are a developer and have a dev server running in parallel.
